version: "3.8"

services:
  db:
    image: postgres:16.1-alpine3.19
    container_name: com617-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/libpostgresql/data

  server:
    image: com617-server
    build:
      context: .
      target: server-dev
      dockerfile: Dockerfile
    container_name: com617-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    image: com617-client
    build:
      context: .
      target: client-dev
      dockerfile: Dockerfile
    container_name: com617-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

networks:
  default:
    name: projecSt-network

volumes:
  db:
    driver: local
