version: "3.8"

services:
  db:
    image: postgres:16.1-alpine3.19
    container_name: com617-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v2.15.2
    container_name: com617-hasura
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@com617-db:5432/postgres
      #HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    restart: always
    depends_on:
      - db

  #server:
  #  image: com617-server
  #  build:
  #    context: .
  #    target: server-dev
  #    dockerfile: Dockerfile
  #  container_name: com617-server
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - ./server:/usr/src/app
  #    - /usr/src/app/node_modules

  client:
    image: com617-client
    build:
      context: .
      target: client-dev
      dockerfile: Dockerfile
    container_name: com617-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    #depends_on:
    #  - server

networks:
  default:
    name: projecSt-network

volumes:
  db:
    driver: local
