DROP TABLE IF EXISTS Trips;
DROP TABLE IF EXISTS Emissions;
DROP TABLE IF EXISTS Users;

DROP TYPE IF EXISTS LATLNG;
DROP TYPE IF EXISTS VEHICLE;

DROP TYPE IF EXISTS vehicle_laden;
DROP TYPE IF EXISTS vehicle_fuel;
DROP TYPE IF EXISTS vehicle_type;
DROP TYPE IF EXISTS vehicle_activity;