name: Cypress Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        working-directory: ./client
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Installation
        working-directory: ./client
        run: npm ci
      - name: Execute E2E tests
        working-directory: ./client
        run: npm run test:e2e
