name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: latest
    container:
      # image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      image: com617.azurecr.io/com617:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
        run: npm run build
        run: npm start
          browser: chrome
